# Config files :3

source=./keyboard.conf
source=./animations.conf
source=./appearance.conf
source=./monitors.conf
source=./tags.conf
source=./animations.conf
source=./effects.conf
source=./layouts.conf
source=./mouse.conf
source=./env.conf
source=./misc.conf
source=./overview.conf
source=./auto-exec.conf
source=./keys.conf
source=./rules.conf
