exec-once=swww-daemon && swww img ~/Pictures/wallpapers/flowers.jpg
exec-once=dunst
exec-once=easyeffects --gapplication-service
exec-once=~/.config/mango/scripts/tag-listener.sh &
exec-once=~/.config/mango/scripts/system-daemon.sh &
exec-once=mlint --watch &
